### ISSUE TITLE
Invoking search on a help page shifts the whole content to the left

### ISSUE THREAD

**Issue by VitGottwald** [neovim/doc#56] opened 2024-04-03 14:18 UTC
Fist of all great job with the docs site and search!

I just tried it for the first time and tried searching and noticed a small glitch.

When I go to a doc page, for example https://neovim.io/doc/user/undo.html#undo-commands and I press CMD+K to invoke the search functionality, the whole content shifts to the right. After closing the search dialog, the content shifts back to the left

![Untitled](https://github.com/neovim/doc/assets/19686979/c2783f74-ecc3-4500-b6e8-4aa1d0e9f67c)
![Untitled2](https://github.com/neovim/doc/assets/19686979/ff11f518-a214-4c78-a283-fa8d0e693fc4)

For some reason this does not happen on the main page https://neovim.io/doc/ .

**Comment by justinmk** [comment] 2024-04-03 20:47
Patch welcome. Surely with all the web devs out there, someone could help with this?

**Comment by Bashamega** [comment] 2024-05-23 09:01
Hello:)
I have tested it on my windows computer and it worked.

**Comment by justinmk** [comment] 2024-05-23 09:21
Yeah, I can't reproduce this. I assume it was fixed by one of the recent CSS changes.

**Closed by justinmk** 2024-05-23 09:21 UTC

**Comment by VitGottwald** [comment] 2024-05-23 11:48
Just tried it and it on https://neovim.io/doc/user/undo.html#undo-commands and I can reproduce it.

**Comment by justinmk** [comment] 2024-05-23 12:49
Well I can't, so without a PR this is wontfix
